name: example
description: An example implementation for a SlidingSheet.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  community_charts_flutter: ^1.0.1

  flutter:
    sdk: flutter

  material_design_icons_flutter: ^6.0.7096
  
  wtf_sliding_sheet: ^0.6.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/maps_screenshot.png